# Generated by Django 6.0.3 on 2026-03-11 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(help_text='GitHub username or organization', max_length=255)),
                ('name', models.CharField(help_text='Repository name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_repos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tracked repositories',
                'ordering': ['owner', 'name'],
                'unique_together': {('user', 'owner', 'name')},
            },
        ),
    ]
