# Generated by Django 5.2.14 on 2026-05-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_personalaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedrepository',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether to include in PR fetching'),
        ),
        migrations.AlterField(
            model_name='personalaccesstoken',
            name='token',
            field=models.CharField(help_text='GitHub fine-grained or classic token', max_length=255),
        ),
    ]
