# Generated by Django 5.2.14 on 2026-06-05 10:50

from django.db import migrations, models


def migrate_auto_refresh_setting(apps, schema_editor):
    """Copy auto_refresh_enabled value to all three new per-tab fields."""
    UserPreferences = apps.get_model('dashboard', 'UserPreferences')
    for prefs in UserPreferences.objects.all():
        if prefs.auto_refresh_enabled:
            prefs.auto_refresh_my_prs = True
            prefs.auto_refresh_review_requests = True
            prefs.auto_refresh_assigned = True
            prefs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='auto_refresh_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='auto_refresh_my_prs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='auto_refresh_review_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_auto_refresh_setting, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userpreferences',
            name='auto_refresh_enabled',
        ),
    ]
