# Generated by Django 6.0.5 on 2026-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_per_tab_auto_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='auto_refresh_interval',
            field=models.PositiveIntegerField(choices=[(1, '1 minute'), (2, '2 minutes'), (5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '1 hour')], default=5),
        ),
    ]
