# Generated by Django 6.0.5 on 2026-07-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_per_tab_auto_refresh_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='pr_list_page_size',
            field=models.PositiveIntegerField(choices=[(25, '25'), (50, '50'), (100, '100'), (0, 'All')], default=25),
        ),
    ]
