# Generated by Django 6.0.5 on 2026-07-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_userpreferences_pr_list_page_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='show_github_status',
            field=models.BooleanField(default=True),
        ),
    ]
